---

csc_prefix_lists:
  - name: PL-GATEWAY-LOOP
    sequence_numbers:
      - sequence: 10
        action: 'permit 2.2.2.7/32'
      - sequence: 20
        action: 'permit 1.1.2.7/32'
      - sequence: 30
        action: 'permit 1.1.2.8/32'

csc_router_bgp:
  peer_groups:
    - name: EVPN-OVERLAY-CORE
      local_as: 65500
      remove_private_as:
        replace_as: true
      remote_as: 65500
      route_map_in: RM-AS65000-EVPN-IN
      route_map_out: RM-AS65000-EVPN-OUT
      route_reflector_client: true
      update_source: Loopback0
      bfd: true
      ebgp_multihop: 15
      send_community: all
  neighbors:
    - ip_address: 172.16.2.0
      peer_group: IPv4-REMOTE-UNDERLAY-PEERS
      description: BB1_UNDERLAY
    - ip_address: 172.16.2.4
      peer_group: IPv4-REMOTE-UNDERLAY-PEERS
      description: BB2_UNDERLAY
    - ip_address: 1.1.0.1
      peer_group:  EVPN-OVERLAY-CORE
      description: BB1_OVERLAY
    - ip_address: 1.1.0.2
      peer_group:  EVPN-OVERLAY-CORE
      description: BB2_OVERLAY
  address_family_evpn:
    peer_groups:
      - name: EVPN-OVERLAY-CORE
        activate: true
        domain_remote: true
  address_family_ipv4:
    peer_groups:
      - name: IPv4-REMOTE-UNDERLAY-PEERS
        activate: true
      - name: EVPN-OVERLAY-CORE
        activate: false
    networks:
      - prefix: "1.1.2.7/32"
      - prefix: "1.1.2.8/32"
      - prefix: "2.2.2.7/32"

csc_ethernet_interfaces:
  - name: Ethernet7
    mtu: 9214
  - name: Ethernet8
    mtu: 9214
