---
type: l3leaf

evpn_multicast: false
underlay_multicast: false

csc_router_bgp:
  bgp:
    bestpath:
      d_path: true
  address_family_evpn:
    domain_identifier: "3:3"

csc_prefix_lists:
  - name: PL-GATEWAY-LOOP
    sequence_numbers:
      - sequence: 10
        action: 'permit 2.2.3.7/32'
      - sequence: 20
        action: 'permit 1.1.3.7/32'
      - sequence: 30
        action: 'permit 1.1.3.8/32'

csc_route_maps:
  - name: RM-AS65000-IPV4-OUT
    sequence_numbers:
      - sequence: 10
        type: 'permit'
        match:
          - 'ip address prefix-list PL-GATEWAY-LOOP'

# csc_vlan_interfaces:
#   - name: 'Vlan4094'
#     mtu: 1500

monitor_connectivity:
  shutdown: false
  vrfs:
      # VRF Name
    - name: Prod
      interface_sets:
        - name: Prod-Vtep-Diag
          interfaces: Loopback101
      hosts:
        - name: A-LEAF7-DiagVtep-Prod
          ip: 10.101.101.7
          local_interfaces: Prod-Vtep-Diag
        - name: B-LEAF7-DiagVtep-Prod
          ip: 10.101.102.7
          local_interfaces: Prod-Vtep-Diag
    - name: Dev
      interface_sets:
        - name: Dev-Vtep-Diag
          interfaces: Loopback102
      hosts:
        - name: A-LEAF7-DiagVtep-Dev
          ip: 10.102.101.7
          local_interfaces: Dev-Vtep-Diag
        - name: B-LEAF7-DiagVtep-Dev
          ip: 10.102.102.7
          local_interfaces: Dev-Vtep-Diag

custom_templates:
  - af-evpn.j2
