---
type: l2leaf

l2leaf:
  defaults:
    platform: "veos"
    mlag_peer_ipv4_pool: 10.253.1.0/31
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
    uplink_switches: [ a-spine1, a-spine2 ]
    uplink_interfaces: [ Ethernet1, Ethernet2 ]
    mlag_interfaces: [ Ethernet5, Ethernet6 ]
  node_groups:
    - group: A-LEAF1_PAIR
      nodes:
        - name: a-leaf1
          id: 1
          mgmt_ip: 192.168.0.13/24
          uplink_switch_interfaces: [ Ethernet1, Ethernet1 ]
        - name: a-leaf2
          id: 2
          mgmt_ip: 192.168.0.14/24
          uplink_switch_interfaces: [ Ethernet2, Ethernet2 ]
    - group: A-LEAF2_PAIR
      nodes:
        - name: a-leaf3
          id: 3
          mgmt_ip: 192.168.0.15/24
          uplink_switch_interfaces: [ Ethernet3, Ethernet3 ]
        - name: a-leaf4
          id: 4
          mgmt_ip: 192.168.0.16/24
          uplink_switch_interfaces: [ Ethernet4, Ethernet4 ]