---
type: l2leaf

l2leaf:
  defaults:
    platform: "veos"
    mlag_peer_ipv4_pool: 10.253.2.0/31
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
    uplink_switches: [ b-spine1, b-spine2 ]
    uplink_interfaces: [ Ethernet1, Ethernet2 ]
    mlag_interfaces: [ Ethernet5, Ethernet6 ]
  node_groups:
    - group: B-LEAF1_PAIR
      nodes:
        - name: b-leaf1
          id: 1
          mgmt_ip: 192.168.0.113/24
          uplink_switch_interfaces: [ Ethernet1, Ethernet1 ]
        - name: b-leaf2
          id: 2
          mgmt_ip: 192.168.0.114/24
          uplink_switch_interfaces: [ Ethernet2, Ethernet2 ]
    - group: B-LEAF2_PAIR
      nodes:
        - name: b-leaf3
          id: 3
          mgmt_ip: 192.168.0.115/24
          uplink_switch_interfaces: [ Ethernet3, Ethernet3 ]
        - name: b-leaf4
          id: 4
          mgmt_ip: 192.168.0.116/24
          uplink_switch_interfaces: [ Ethernet4, Ethernet4 ]