---
mgmt_gateway: 10.0.0.1
mgmt_interface: Management0

## disabled due to a bug
## try if you need a challenge =)
# eos_cli: |
#   interface Management0
#       no lldp receive
#       no lldp transmit

dns_settings:
  domain: avd.lab
  servers:
    - ip_address: 8.8.8.8
      vrf: MGMT

# NTP servers
ntp_settings:
  server_vrf: use_mgmt_interface_vrf
  servers:
    - name: time.google.com
    - name: time.windows.com
    - name: time.apple.com

aaa_settings:
  # Local Users
  local_users:
    - name: arista
      privilege: 15
      role: network-admin
      sha512_password: "{{ ansible_password | password_hash(rounds=5000, salt=1) }}"
  # AAA Authorization Settings
  authorization:
    exec:
      default: local

ansible_user: arista
ansible_password: arista
ansible_network_os: arista.eos.eos
# Configure privilege escalation
ansible_become: true
ansible_become_method: enable
# HTTPAPI configuration
ansible_connection: httpapi
ansible_httpapi_port: 443
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_python_interpreter: $(which python3)
avd_data_validation_mode: error

cv_settings:
  cvaas:
    enabled: true
    clusters:
      - name: cvaas
        region: staging
        token_file: "/mnt/flash/cv-onboarding-token"
  terminattr:
    disable_aaa: true
