---

fabric_name: DOMAIN_A_FABRIC

bgp_distance:
  external_routes: 20
  internal_routes: 200
  local_routes: 200

bgp_graceful_restart:
  enabled: true
  restart_time: 300

bgp_peer_groups:
  ipv4_underlay_peers:
    name: LOCAL-IPV4-PEERS
    password: DGMjRCIj8IZAFhehikpUIQ==
  mlag_ipv4_underlay_peer:
    name: MLAG-IPV4-PEER
    password: CRkxra9QRmU5k9/wECPlUA==
  evpn_overlay_peers:
    name: LOCAL-EVPN-PEERS
    password: WzKnNSduqwPYvUePYIh40g==
  evpn_overlay_core:
    name: REMOTE-EVPN-PEERS
    password: IO6gE/ln7Sp2wt33WX/Asg==

bgp_update_wait_install: true

evpn_import_pruning: true

evpn_multicast: true

fabric_ip_addressing:
  mlag:
    algorithm: same_subnet

router_id_loopback_description: "Globally Unique Address"

default_vrf_diag_loopback_description: "Per-VRF Unique Loopback"

underlay_multicast: true

vtep_loopback_description: "VTEP IP"

###################################################
# Customized Structured Config                    #
###################################################
csc_vtep_dhcp_relay:
  tunnel_requests_disabled: true
  mlag_peerlink_requests_disabled: true

csc_vtep_ip_dhcp_relay:
  information_option: true

csc_evpn_gw_bgp:
  address_family_ipv4:
    peer_groups:
      - name: REMOTE-IPV4-PEERS
        activate: true
  address_family_evpn:
    domain_identifier: '1:1'
    domain_identifier_remote: '99:99'
  bgp:
    bestpath:
      d_path: true
  peer_groups:
    - name: REMOTE-IPV4-PEERS
      password: dkvBq1jk4inJHsHfMjYRnQ==
      remote_as: 65000
      route_map_out: RM-AS65000-IPV4-OUT
      send_community: all
    - name: REMOTE-EVPN-PEERS
      local_as: 65000

csc_evpn_gw_prefix_lists:
  - name: PL-GATEWAY-LOOP
    sequence_numbers:
      - sequence: 10
        action: permit 2.2.1.7/32
      - sequence: 20
        action: permit 1.1.1.7/32
      - sequence: 30
        action: permit 1.1.1.8/32

csc_evpn_gw_route_maps:
  - name: RM-AS65000-IPV4-OUT
    sequence_numbers:
      - sequence: 10
        type: permit
        match:
          - ip address prefix-list PL-GATEWAY-LOOP

csc_aleaf7_bgp:
  neighbors:
    - ip_address: 172.16.1.0
      peer_group: REMOTE-IPV4-PEERS
      description: BB1.IPV4
    - ip_address: 172.16.1.4
      peer_group: REMOTE-IPV4-PEERS
      description: BB2.IPV4

csc_aleaf8_bgp:
  neighbors:
    - ip_address: 172.16.1.2
      peer_group: REMOTE-IPV4-PEERS
      description: BB1.IPV4
    - ip_address: 172.16.1.6
      peer_group: REMOTE-IPV4-PEERS
      description: BB2.IPV4

###################################################
# DOMAIN A SPINES                                 #
###################################################
spine:
  defaults:
    platform: cEOS-LAB
    bgp_as: 65100
    loopback_ipv4_pool: 1.1.1.0/24
  nodes:
    - name: A-SPINE1
      id: 201
      mgmt_ip: 172.100.100.101/24
    - name: A-SPINE2
      id: 202
      mgmt_ip: 172.100.100.102/24
    - name: A-SPINE3
      id: 203
      mgmt_ip: 172.100.100.103/24
    - name: A-SPINE4
      id: 204
      mgmt_ip: 172.100.100.104/24

##################################################
# DOMAIN A LEAFS                                 #
##################################################
l3leaf:
  defaults:
    platform: cEOS-LAB
    loopback_ipv4_pool: 1.1.1.0/24
    vtep_loopback_ipv4_pool: 2.2.1.0/24
    uplink_interfaces: [Ethernet1, Ethernet2, Ethernet3, Ethernet4]
    uplink_switches: [A-SPINE1, A-SPINE2, A-SPINE3, A-SPINE4]
    uplink_ipv4_pool: 192.168.0.0/24
    mlag_interfaces: [Ethernet5, Ethernet6]
    mlag_peer_ipv4_pool: 169.254.0.0/31
    mlag_peer_l3_ipv4_pool: 192.0.0.0/31
    mlag_port_channel_id: 1000
    virtual_router_mac_address: 00:1c:73:00:00:01
    spanning_tree_mode: mstp
    spanning_tree_priority: 0
    structured_config:
      dhcp_relay: "{{ csc_vtep_dhcp_relay }}"
      ip_dhcp_relay: "{{ csc_vtep_ip_dhcp_relay }}"
  node_groups:
########################################################
# DOMAIN A POD 1                                       #
########################################################
    - group: POD1
      bgp_as: 65112
      filter:
        tags: ['BLUE', 'ORANGE']
      nodes:
        - name: A-LEAF1
          id: 1
          mgmt_ip: 172.100.100.105/24
          uplink_switch_interfaces: [Ethernet1, Ethernet1, Ethernet1, Ethernet1]
        - name: A-LEAF2
          id: 2
          mgmt_ip: 172.100.100.106/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2, Ethernet2, Ethernet2]
########################################################
# DOMAIN A POD 2                                       #
########################################################
    - group: POD2
      filter:
        tags: ['BLUE', 'ORANGE', 'YELLOW']
      bgp_as: 65134
      nodes:
        - name: A-LEAF3
          id: 3
          mgmt_ip: 172.100.100.107/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3, Ethernet3, Ethernet3]
        - name: A-LEAF4
          id: 4
          mgmt_ip: 172.100.100.108/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4, Ethernet4, Ethernet4]
########################################################
# DOMAIN A POD 3                                       #
########################################################
    - group: POD3
      bgp_as: 65156
      filter:
        tags: ['BROWN']
      nodes:
        - name: A-LEAF5
          id: 5
          mgmt_ip: 172.100.100.109/24
          uplink_switch_interfaces: [Ethernet5, Ethernet5, Ethernet5, Ethernet5]
        - name: A-LEAF6
          id: 6
          mgmt_ip: 172.100.100.110/24
          uplink_switch_interfaces: [Ethernet6, Ethernet6, Ethernet6, Ethernet6]
########################################################
# DOMAIN A POD 4 (Border Leaf / EVPN Gateway)          #
########################################################
    - group: POD4
      bgp_as: 65178
      evpn_gateway:
        evpn_l2:
          enabled: true
        evpn_l3:
          enabled: true
        remote_peers:
          - hostname: BB1
            ip_address: 1.1.0.1
            bgp_as: 65000
          - hostname: BB2
            ip_address: 1.1.0.2
            bgp_as: 65000
      structured_config:
        router_bgp: "{{ csc_evpn_gw_bgp }}"
        prefix_lists: "{{ csc_evpn_gw_prefix_lists }}"
        route_maps: "{{ csc_evpn_gw_route_maps }}"
      nodes:
        - name: A-LEAF7
          id: 7
          mgmt_ip: 172.100.100.111/24
          uplink_switch_interfaces: [Ethernet7, Ethernet7, Ethernet7, Ethernet7]
          structured_config:
            router_bgp: "{{ csc_aleaf7_bgp }}"
        - name: A-LEAF8
          id: 8
          mgmt_ip: 172.100.100.112/24
          uplink_switch_interfaces: [Ethernet8, Ethernet8, Ethernet8, Ethernet8]
          structured_config:
            router_bgp: "{{ csc_aleaf8_bgp }}"
##########################################################
# DCI Connectivity                                       #
##########################################################
l3_edge:
  p2p_links:
    - nodes: [A-LEAF7, BB1]
      interfaces: [Ethernet7, Ethernet1]
      subnet: 172.16.1.0/31
      ip:
        - 172.16.1.1/31
        - 172.16.1.0/31
      include_in_underlay_protocol: false

    - nodes: [A-LEAF7, BB2]
      interfaces: [Ethernet8, Ethernet1]
      subnet: 172.16.1.4/31
      ip:
        - 172.16.1.5/31
        - 172.16.1.4/31
      include_in_underlay_protocol: false

    - nodes: [A-LEAF8, BB1]
      interfaces: [Ethernet7, Ethernet1]
      subnet: 172.16.1.2/31
      ip:
        - 172.16.1.3/31
        - 172.16.1.2/31
      include_in_underlay_protocol: false

    - nodes: [A-LEAF8, BB2]
      interfaces: [Ethernet8, Ethernet1]
      subnet: 172.16.1.6/31
      ip:
        - 172.16.1.7/31
        - 172.16.1.6/31
      include_in_underlay_protocol: false
