---
type: l3leaf


cv_tags_topology_type: leaf
evpn_multicast: true

dhcp_relay:
  tunnel_requests_disabled: true

csc_router_bgp:
  address_family_evpn:
    route:
      import_ethernet_segment_ip_mass_withdraw: true
      export_ethernet_segment_ip_mass_withdraw: true
# variables used in custom templates
_prod_multicast_group_overlay: 239.0.20.101
_prod_multicast_group_encap: 232.1.1.20

_dev_multicast_group_overlay: 239.0.60.101
_dev_multicast_group_encap: 232.2.2.60

_evpn_aa_multihoming: true
