---

- name: Build Switch configuration
  hosts: FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp

  tasks:

    - name: generate intended variables
      tags: [build, generate]
      ansible.builtin.import_role:
        name: arista.avd.eos_designs

    - name: generate device intended config and documentation
      tags: [build, generate]
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen

    - name: gen act topo
      ansible.builtin.import_role:
        name: act_topology_gen
      vars:
        connected_endpoints: true
