---

# AAA Authorization Settings
aaa_authorization:
  exec:
    default: local

# Global ARP Timer
arp:
  aging:
    timeout_default: 1500

avd_data_validation_mode: error

# Clock Timezone
clock:
  timezone: America/Detroit

dns_domain: aclabs.lab

# Event Monitor in EOS
event_monitor:
  enabled: true

# Source interface and VRF for DNS
ip_domain_lookup:
  source_interfaces:
    - name: Management0
      vrf: MGMT

# Source interface and VRF for HTTP(S)
ip_http_client_source_interfaces:
  - name: Management0
    vrf: MGMT

# DNS Servers
ip_name_servers:
  - ip_address: 8.8.8.8
    vrf: MGMT

# Source interface and VRF for SSH
ip_ssh_client_source_interfaces:
  - name: Management0
    vrf: MGMT

# Local Users
local_users:
  - name: arista
    privilege: 15
    role: network-admin
    sha512_password: $6$Ap6u4I1WR/jMoNKe$LPLoHgIXFg5kiGPDWGF0w5lVVuOZZ4T15cIBbNxE2ykqh98uVvsi9jPdybkbTXBTZFzi3haaPJVaGVwnpuck40
  - name: admin
    privilege: 15
    role: network-admin
    sha512_password: $6$eucN5ngreuExDgwS$xnD7T8jO..GBDX0DUlp.hn.W7yW94xTjSanqgaQGBzPIhDAsyAl9N4oScHvOMvf07uVBFI4mKMxwdVEUVKgY/.

# Global MAC Aging Timer
mac_address_table:
  aging_time: 1800

# Enable eAPI
management_api_http:
  enable_http: false
  enable_https: true
  enable_vrfs:
    - name: VRF

# Enable SSH
management_ssh:
  vrfs:
    - name: default
      enable: true
    - name: MGMT
      enable: true

# Out of Band Management
mgmt_gateway: 172.100.100.1
mgmt_interface: Management0
mgmt_interface_vrf: MGMT

# NTP Servers
ntp:
  local_interface:
    name: Management0
    vrf: MGMT
  servers:
    - name: time.google.com
      iburst: true
      preferred: true
      vrf: MGMT
    - name: time.windows.com
      vrf: MGMT
      iburst: true
      preferred: false
    - name: time.apple.com
      iburst: true
      preferred: false
      vrf: MGMT

# Global IP MTU for Point-to-Point links
p2p_uplinks_mtu: 9214

# Default mode of "routed" interfaces
switchport_default:
  mode: routed

ansible_user: admin
ansible_password: admin
ansible_network_os: arista.eos.eos
# Configure privilege escalation
ansible_become: true
ansible_become_method: enable
# HTTPAPI configuration
ansible_connection: ansible.netcommon.httpapi
ansible_httpapi_port: 443
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_python_interpreter: $(which python3)
avd_data_validation_mode: error
