---
dc_name: domain-d

pod_name: pod-d

spine:
  defaults:
    platform: vEOS-lab
    loopback_ipv4_pool: 1.1.4.0/24
    loopback_ipv6_pool: 2001:db8:d:1::0/64
    loopback_ipv6_offset: 0
    bgp_as: 65400

  nodes: 
    - name: D-SPINE1
      id: 201 
      mgmt_ip: 192.168.0.21/24 
    - name: D-SPINE2
      id: 202
      mgmt_ip: 192.168.0.22/24
    - name: D-SPINE3
      id: 203
      mgmt_ip: 192.168.0.23/24 
    - name: D-SPINE4
      id: 204
      mgmt_ip: 192.168.0.24/24

l3leaf:
  defaults:
    platform: vEOS-lab
    uplink_ipv4_pool: 192.168.1.0/24
    loopback_ipv4_pool: 1.1.4.0/24
    loopback_ipv6_pool: 2001:db8:d:1::0/64
    loopback_ipv4_offset: 0
    loopback_ipv6_offset: 0
    vtep_loopback_ipv4_pool: 2.2.4.0/24 
    uplink_interfaces: ['Ethernet1', 'Ethernet2', 'Ethernet3', 'Ethernet4'] 
    uplink_switches: ['D-SPINE1', 'D-SPINE2', 'D-SPINE3', 'D-SPINE4']
    mlag_interfaces: ['Ethernet5', 'Ethernet6']
    mlag_peer_ipv4_pool: 169.254.0.0/31
    mlag_peer_l3_ipv4_pool: 192.0.0.0/31
    mlag_port_channel_id: 1000
    mlag_domain_id: "100"
    mlag_ibgp_origin_incomplete: true
    virtual_router_mac_address: 00:1c:73:00:00:01
    spanning_tree_priority: 0
    spanning_tree_mode: mstp
    filter:
      tenants:
        - DUALSTACK
    structured_config:
      spanning_tree:
        edge_port:
          bpduguard_default: true
          
  node_groups: 
    - group: DOMAIN_D_LA
      bgp_as: 65412
      filter:
        only_vlans_in_use: true
      nodes:
        - name: D-LEAF1
          id: 1
          mgmt_ip: 192.168.0.129/24
          mlag_peer_vlan_structured_config:
            ipv6_address: 2001:db8::1/64
          uplink_switch_interfaces: 
            - Ethernet1
            - Ethernet1
            - Ethernet1
            - Ethernet1
        - name: D-LEAF2
          id: 2
          mgmt_ip: 192.168.0.130/24
          mlag_peer_vlan_structured_config:
            ipv6_address: 2001:db8::2/64
          uplink_switch_interfaces:
            - Ethernet2
            - Ethernet2
            - Ethernet2
            - Ethernet2
    - group: DOMAIN_D_LB
      bgp_as: 65434
      filter:
        only_vlans_in_use: true
      nodes:
        - name: D-LEAF3
          id: 3
          mgmt_ip: 192.168.0.131/24
          mlag_peer_vlan_structured_config:
            ipv6_address: 2001:db8::1/64
          uplink_switch_interfaces: 
            - Ethernet3
            - Ethernet3
            - Ethernet3
            - Ethernet3
        - name: D-LEAF4
          id: 4
          mgmt_ip: 192.168.0.132/24
          mlag_peer_vlan_structured_config:
            ipv6_address: 2001:db8::2/64
          uplink_switch_interfaces:
            - Ethernet4
            - Ethernet4
            - Ethernet4
            - Ethernet4
    - group: DOMAIN_D_LC
      bgp_as: 65456
      filter:
        only_vlans_in_use: true
      nodes:
        - name: D-LEAF5
          id: 5
          mgmt_ip: 192.168.0.133/24
          mlag_peer_vlan_structured_config:
            ipv6_address: 2001:db8::1/64
          uplink_switch_interfaces: 
            - Ethernet5
            - Ethernet5
            - Ethernet5
            - Ethernet5
        - name: D-LEAF6
          id: 6
          mgmt_ip: 192.168.0.134/24
          mlag_peer_vlan_structured_config:
            ipv6_address: 2001:db8::2/64
          uplink_switch_interfaces:
            - Ethernet6
            - Ethernet6
            - Ethernet6
            - Ethernet6
    - group: DOMAIN_D_EVPNGW
      bgp_as: 65478
      mlag: false
      evpn_gateway:
        # Specific BGP EVPN Gateway functionality for route types 2 (MAC-IP), 3 (IMET) and 5 (IP-PREFIX) can be enabled separately as needed.
        evpn_l2:
          enabled: true
        evpn_l3:
          enabled: true
          inter_domain: true
        remote_peers:
          - hostname: BB1
            bgp_as: 65000
            ip_address: 1.1.0.1
          - hostname: BB2
            bgp_as: 65000
            ip_address: 1.1.0.2
      nodes:
        - name: D-LEAF7
          id: 7
          mgmt_ip: 192.168.0.135/24
          uplink_switch_interfaces: 
            - Ethernet7
            - Ethernet7
            - Ethernet7
            - Ethernet7
        - name: D-LEAF8
          id: 8
          mgmt_ip: 192.168.0.136/24
          uplink_switch_interfaces:
            - Ethernet8
            - Ethernet8
            - Ethernet8
            - Ethernet8
