---
om_prefix:
 - om_
aaa_settings:
  local_users:
    - name: admin
      privilege: 15
      role: network-admin
      sha512_password: "$6$7GTxsrRjnwheeKfR$zhJ8qycVjAJz41rf5JRSfWIzp93IL5WL7sMS/Taz1yfShz.MAnoajCf7R2n1/EZW7PN5QA3Huayl0lVQesBYN1"

dns_settings:
  servers:
    - ip_address: 1.1.1.1
      vrf: MGMT
    - ip_address: 8.8.8.8
      vrf: MGMT

ntp_settings:
  server_vrf: MGMT
  servers:
  - name: time.google.com

om_spanning_tree:
  mode: mstp

# hardcoding management0 for cEOS lab compatibility (default: Management1)
mgmt_interface: Management0
mgmt_gateway: 172.144.100.1
mgmt_interface_vrf: MGMT

# Management eAPI | Required for this Lab
om_management_api_http:
  https_ssl_profile: eAPI

# Management security required for SSL profile with strong ciphers
om_management_security:
  ssl_profiles:
    - name: eAPI
      certificate:
        file: eAPI.crt
        key: eAPI.key
      cipher_list: 'HIGH:!eNULL:!aNULL:!MD5:!ADH:!ANULL'

# Management GNMI | Optional
om_management_api_gnmi:
  provider: "eos-native"
  transport:
    grpc:
    - name: MGMT
      vrf: MGMT
      notification_timestamp: "send-time"
    - name: default
      notification_timestamp: "send-time"
