---

- name: Build Switch configuration
  hosts: all
  gather_facts: false

  tasks:

    - name: Generate Structured Variables per Device
      ansible.builtin.import_role:
        name: arista.avd.eos_designs

    - name: Generate Intended Config and Documentation
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen
