---
name: Create alpine host container image

on:
  push:
    branches: ['**']  # branches will be filtered in the jobs
    paths:
      - .github/workflows/container_build_host_alpine.yml
      - .github/workflows/container_build_child.yml
      - containers/host-alpine/**
  workflow_dispatch:
    branches: ['**']  # branches will be filtered in the jobs

jobs:
  build-demo-container:
    # fork - build container from any branch for testing
    # parent repo - build on main branch only
    if: github.repository != 'aristanetworks/acLabs' || github.ref == 'refs/heads/main'
    uses: ./.github/workflows/container_build_child.yml
    with:
      container_name: "host-alpine"
      image_tags: "latest"
      from_image: "alpine"
      from_variant: "latest"
