---

dc_name: domain-b

pod_name: pod-b

spine:
  defaults:
    platform: vEOS-lab 
    loopback_ipv4_pool: 1.1.2.0/24
    isis_system_id_prefix: '0000.0000'
    bgp_as: 65200
    raw_eos_cli: |
      agent KernelFib environment KERNELFIB_PROGRAM_ALL_ECMP='true'
  nodes: 
    - name: B-SPINE1
      id: 201 
      mgmt_ip: 192.168.0.15/24 
    - name: B-SPINE2
      id: 202
      mgmt_ip: 192.168.0.16/24
    - name: B-SPINE3
      id: 203
      mgmt_ip: 192.168.0.17/24 
    - name: B-SPINE4
      id: 204
      mgmt_ip: 192.168.0.18/24

l3leaf:
  defaults:
    platform: vEOS-lab 
    loopback_ipv4_pool: 1.1.2.0/24
    loopback_ipv4_offset: 0
    vtep_loopback_ipv4_pool: 2.2.2.0/24
    uplink_interfaces: ['Ethernet1', 'Ethernet2', 'Ethernet3', 'Ethernet4'] 
    uplink_switches: ['B-SPINE1', 'B-SPINE2', 'B-SPINE3', 'B-SPINE4']
    uplink_structured_config:
      ip_address: "unnumbered Loopback0"
    uplink_ipv4_pool: 192.168.1.0/24
    virtual_router_mac_address: 00:1c:73:00:00:01
    spanning_tree_root_super: true
    spanning_tree_mode: rapid-pvst
    bgp_as: 65200
    isis_system_id_prefix: '0000.0000'
    link_tracking:
      enabled: true
      groups:
        - name: CORE-LINKS
    filter:
      tenants:
        - Prod
        - Dev
    raw_eos_cli: |
      agent KernelFib environment KERNELFIB_PROGRAM_ALL_ECMP='true'
  nodes:
    - name: B-LEAF1
      id: 1
      filter:
        only_vlans_in_use: true
      mgmt_ip: 192.168.0.111/24
      uplink_switch_interfaces: 
        - Ethernet1
        - Ethernet1
        - Ethernet1
        - Ethernet1
    - name: B-LEAF2
      id: 2
      filter:
        only_vlans_in_use: true
      mgmt_ip: 192.168.0.112/24
      uplink_switch_interfaces:
        - Ethernet2
        - Ethernet2
        - Ethernet2
        - Ethernet2
    - name: B-LEAF3
      id: 3
      filter:
        only_vlans_in_use: true
      mgmt_ip: 192.168.0.113/24
      uplink_switch_interfaces: 
        - Ethernet3
        - Ethernet3
        - Ethernet3
        - Ethernet3
    - name: B-LEAF4
      id: 4
      filter:
        only_vlans_in_use: true
      mgmt_ip: 192.168.0.114/24
      uplink_switch_interfaces:
        - Ethernet4
        - Ethernet4
        - Ethernet4
        - Ethernet4
    - name: B-LEAF5
      id: 5
      filter:
        only_vlans_in_use: true
      mgmt_ip: 192.168.0.115/24
      uplink_switch_interfaces: 
        - Ethernet5
        - Ethernet5
        - Ethernet5
        - Ethernet5
    - name: B-LEAF6
      id: 6
      filter:
        only_vlans_in_use: true
      mgmt_ip: 192.168.0.116/24
      uplink_switch_interfaces:
        - Ethernet6
        - Ethernet6
        - Ethernet6
        - Ethernet6
  node_groups:       
    - group: DOMAIN_B_EVPNGW
      bgp_as: 65200
      mlag: false
      filter:
        tenants:
          - EVPNGW
      evpn_gateway:
    # Specific BGP EVPN Gateway functionality for route types 2 (MAC-IP), 3 (IMET) and 5 (IP-PREFIX) can be enabled separately as needed.
        evpn_l2:
          enabled: true
        evpn_l3:
          enabled: true
          inter_domain: true
        remote_peers:
          - hostname: BB1
            bgp_as: 65500
            ip_address: 1.1.0.1
          - hostname: BB2
            bgp_as: 65500
            ip_address: 1.1.0.2
      raw_eos_cli: |
        dhcp relay
          mlag peer-link requests disabled
        agent KernelFib environment KERNELFIB_PROGRAM_ALL_ECMP='true'
      nodes:
        - name: B-LEAF7
          id: 7
          mgmt_ip: 192.168.0.117/24
          uplink_switch_interfaces: 
            - Ethernet7
            - Ethernet7
            - Ethernet7
            - Ethernet7
        - name: B-LEAF8
          id: 8
          mgmt_ip: 192.168.0.118/24
          uplink_switch_interfaces:
            - Ethernet8
            - Ethernet8
            - Ethernet8
            - Ethernet8

l2leaf:
  defaults:
    platform: vEOS-lab
    uplink_interfaces: ['Ethernet1', 'Ethernet2']
    uplink_switches: ['B-LEAF5','B-LEAF6']
    spanning_tree_mode: rapid-pvst
    raw_eos_cli: |
      agent KernelFib environment KERNELFIB_PROGRAM_ALL_ECMP='true'
  nodes:
    - name: B-SW1
      id: 1
      mgmt_ip: 192.168.0.119/24
      uplink_switch_interfaces:
        - Ethernet7
        - Ethernet7
      
